name: Build Wheels (CPU only)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-wheels:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest }   # Linux → manylinux wheels
          - { os: macos-latest }    # macOS → native wheels

    env:
      # Build these Python versions
      CIBW_BUILD: "cp310-* cp311-* cp312-*"
      CIBW_SKIP: "*-musllinux*"

      # Linux: produce manylinux-tagged wheels (2_28 by default)
      CIBW_ARCHS_LINUX: "x86_64"
      CIBW_MANYLINUX_X86_64_IMAGE: "quay.io/pypa/manylinux_2_28_x86_64"
      CIBW_REPAIR_WHEEL_COMMAND_LINUX: "auditwheel repair -w {dest_dir} {wheel}"

      # macOS: ARM runners by default; build arm64 wheels
      CIBW_ARCHS_MACOS: "arm64"
      CIBW_ENVIRONMENT_MACOS: "MACOSX_DEPLOYMENT_TARGET=11.0"

      # toolchain / build speed
      CMAKE_BUILD_PARALLEL_LEVEL: "4"

      # If your build needs PyTorch headers even for CPU, install it before build:
      CIBW_BEFORE_BUILD_LINUX: |
        python -m pip install -U pip wheel build ninja packaging
        pip install torch==2.4.1 torchvision==0.19.1 --index-url https://download.pytorch.org/whl/cpu
      CIBW_BEFORE_BUILD_MACOS: |
        python -m pip install -U pip wheel build ninja packaging
        pip install torch==2.4.1 torchvision==0.19.1 --index-url https://download.pytorch.org/whl/cpu

      # Your package can read these if needed
      CIBW_ENVIRONMENT: "FORCE_CUDA=0 JATIC_TORCH_VARIANT=cpu"

      # Optional: increase verbosity a bit
      CIBW_BUILD_VERBOSITY: "1"

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up driver Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install cibuildwheel
        run: python -m pip install -U cibuildwheel

      - name: Build wheels (manylinux on Linux, native on macOS)
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Build sdist (once on Linux)
        if: runner.os == 'Linux'
        run: |
          python -m pip install -U build
          python -m build --sdist --outdir wheelhouse

      - name: Smoke test one built wheel
        shell: bash
        run: |
          whl=$(ls wheelhouse/*.whl | head -n1)
          python -m pip install "$whl"
          python - <<'PY'
          import importlib
          pkg = importlib.import_module("<your_top_level_package_name>")
          print("Import OK:", pkg.__name__)
          PY

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*
          if-no-files-found: error
