name: Build Wheels

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }} (py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12']
    env:
      FORCE_CUDA: "0"  # CPU-only build
      CMAKE_BUILD_PARALLEL_LEVEL: "4"

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive   # <-- IMPORTANT
          fetch-depth: 0

      # (Optional, belt & suspenders) If you prefer a separate step:
      # - name: Init submodules
      #   run: git submodule update --init --recursive

      - name: Sanity check vendored Detectron2 sources
        run: |
          ls -la src/jatic_dota/_vendor/detectron2/detectron2/layers || true
          ls -la src/jatic_dota/_vendor/detectron2/detectron2/layers/csrc || true
          python - <<'PY'
          import os, sys
          p="src/jatic_dota/_vendor/detectron2/detectron2/layers/csrc"
          ok = os.path.isdir(p) and any(fn.endswith((".cpp",".cu")) for dirpath,_,files in os.walk(p) for fn in files)
          sys.exit(0 if ok else 1)
          PY

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: macOS build flags
        if: runner.os == 'macOS'
        run: |
          echo "MACOSX_DEPLOYMENT_TARGET=11.0" >> $GITHUB_ENV
          echo "ARCHFLAGS=-arch arm64" >> $GITHUB_ENV
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV

      - name: Install build deps + CPU Torch
        run: |
          python -m pip install --upgrade pip
          pip install "setuptools>=68" wheel build ninja packaging
          pip install torch==2.4.1 torchvision==0.19.1

      - name: Build wheel (non-isolated so Torch is visible)
        run: python -m build --wheel --no-isolation -v

      - name: Build sdist (single run)
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
        run: python -m build --sdist --no-isolation -v

      - name: Smoke test install
        run: |
          WHEEL_FILE=$(ls dist/*.whl)
          pip install "$WHEEL_FILE[all]"
          python -c "import jatic_dota; print('import ok')"
          python -c "from jatic_dota import inference; print('inference ok')"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/*.whl
          if-no-files-found: error

      - name: Upload sdist
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
          if-no-files-found: error
